# Generated by Django 4.2.7 on 2023-11-06 23:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None), size=None)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('date', models.DateField()),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
